export const ASYNC_STORAGE_KEY = 'UdaciCards:key3'

export const GET_DECKS_REQUEST = 'GET_DECKS_REQUEST'
export const GET_DECKS_RESPONSE = 'GET_DECKS_RESPONSE'
export const GET_DECKS_ERROR = 'GET_DECKS_ERROR'

export const SAVE_DECK_TITLE_REQUEST = 'SAVE_DECK_TITLE_REQUEST'
export const SAVE_DECK_TITLE_RESPONSE = 'SAVE_DECK_TITLE_RESPONSE'
export const SAVE_DECK_TITLE_ERROR = 'SAVE_DECK_TITLE_ERROR'

export const ADD_CARD_TO_DECK_REQUEST = 'ADD_CARD_TO_DECK_REQUEST'
export const ADD_CARD_TO_DECK_RESPONSE = 'ADD_CARD_TO_DECK_RESPONSE'
export const ADD_CARD_TO_DECK_ERROR = 'ADD_CARD_TO_DECK_ERROR'

